.TH qiv 1 "25 August 2007" "0.4" "qiv manual"
.SH NAME
pqiv \- quick image viewer
.SH SYNOPSIS
.B qiv [options] <file(s) or folder(s)>
.SH DESCRIPTION
pqiv is a really simple image viewer inspired by qiv.
.SH OPTIONS
.TP
.B -i
Suppress the yellow info box in pqiv
.TP
.B -f
Start pqiv in fullscreen mode
#ifndef NO_FADING
.TP
.B -F
Make qiv fade between images. Currently this does only work for images of equal size.
#endif
.TP
.B -s
Auto start slide show
#ifndef NO_SORTING
.TP
.B -n
Sort the file list using natsort
#endif
.TP
.B -d n
Interval for the slideshow function, in seconds
.TP
.B -t
Do not shrink image(s) larger than the screen to fit
.TP
.B -r
Read filename(s) from STDIN.
.TP
.B -c
pqiv will draw this well-known chessboard background for transparent images per
default. Use this option to deactivate this behaviour. If you use this option
twice (and your wm supports it), it will cause the window to be transparent.
.TP
.B -w
Watch open files for changes and reload them if necessary
.TP
.B -z n
Set initial zoom level in percent. This is only useful in conjunction with -t.
.TP
-p n
Select interpolation type for resizing operations. Valid values for n:
.br
.po 5
1: GDK_INTERP_NEAREST, copy the nearest pixel value
.br
2: GDK_INTERP_TILES, tile the image
.br
3: GDK_INTERP_BILINEAR, use bilinear interpolation
.br
4: GDK_INTERP_HYPER, use hyper interpolation
.br
.po 0
.TP
.B -P left,top
Set initial window position. Defaults to center of screen.
#ifndef NO_COMMANDS
.TP
.B -<n>
Use those options (n \in 0..9) to define a command, which will be executed when
you press the corresponding key in pqiv.
.br
.po 5
Prepend the command with
.B >
to show the command's output in a dialog window.
.br
Prepend the command with
.B |
to let pqiv pipe the displayed image to your command and read/reload it from
the command's output.
.br
.po 0
#endif
.PP
The contents of
.B ~/.pqivrc
will be prepended to pqiv's argv. So if you want to make an interval of 1 second
the default for pqiv, put
.nf
	-d1
.fi
into that file.

pqiv will display all files you specified on the command line. Directories will
be searched recursively for files supported by gtk+
(for example: bmp, gif, jpeg, png, wbmp, xpm, svg). Unless you specified
.B -r
the special file
.B -
will cause pqiv to read a file from stdin.
.SH USAGE
In pqiv, you can use both mouse and keyboard to navigate through the images. Execute
.B qiv -h
to get more information on the key bindings.
.SH AUTHOR
.nf
Phillip Berndt (mail at pberndt dot com)
.nf
.fi
The original qiv authors are listed on
.I http://www.klografx.net/qiv/index2.html
