.TH qiv 1 "15 April 2007" "0.1" "qiv manual"
.SH NAME
pqiv \- a python replacement for qiv
.SH SYNOPSIS
.B qiv [-h] [-i] [-f] [-b] [-s n] [-t] <file(s)>
.SH DESCRIPTION
pqiv is a really simple image viewer inspired by qiv. Run
.B qiv -h
and
.B qiv -b 
for information on how to use it.
.SH AUTHOR
.nf
Phillip Berndt (mail at pberndt dot com)
.nf
.fi
The original qiv authors are listed on
.I http://www.klografx.net/qiv/index2.html
