.TH qiv 1 "25 August 2007" "0.4" "qiv manual"
.SH NAME
pqiv \- quick image viewer
.SH SYNOPSIS
.B qiv [-i] [-s] [-f] [-d n] [-r] [-t] <file(s) or folder(s)>
.SH DESCRIPTION
pqiv is a really simple image viewer inspired by qiv. Run
.B qiv -h
for information on how to use it.
.SH AUTHOR
.nf
Phillip Berndt (mail at pberndt dot com)
.nf
.fi
The original qiv authors are listed on
.I http://www.klografx.net/qiv/index2.html
